---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-secret
spec:
  encryptedData:
    redis-password: AgCZUekJgw+dOigxoEW/XVI2+TCZK8Gq9tcxXjTAMqlWjF9U8mBer+lHgM1kZc8mVJW879+mEdOZv6VWwM1ssncvHS17Pm5c2mnpIa/JsSnwrJQKO6Sysran+7ecO1TyjkadADXY35/Mwk1kJMFlVx6a76pXs66WREWuF2eWs5UfMDCY0TBW0PdSlJKQqC56zHK0gcqoSr9z268YZba6OdTp1HBlQoAA/iD0s3LymSbyWMUHpMk2USbUETnDkUMyWO94AHkMoeitYHHiguu/ifRd1wJpr/a2mfPe3hyApy8MuPjzDdV0VzyqOz7uPl3zCXLYU8IwXqkw/G5ogljd7iY3QzHMWBeNIfofFRyawM2VvjtyStRRWkwUjMi0krja8CagDkPZUFY1utSNz1Dx/owF5Sf14cHuJFBdusssF/+K7hr7DIIqxPJ0ApI0sCLK9quScAUGDWOV/d2MZ1KwAtydQJfOdjJxYeFgWnONdz9ZdQPr23nkyhBZ3hGT2BQaEIYxWJ3zUP0scKCfVmNtTi+wwypTWmOhCv/tD5fRyWfpVaUoBOBGAUtxO2lE61F+WrBmKYrySq3MTYk5Jaj50r5d5njo68quv8bEz6yuwO0mZwsObm4kfpZTvttneAT6ToDLn3IDKq3fZDvYY14Khw/5vq0f9mexBbeeldK0Iwmcj5GVij+YanYrngIZDKbwfdY4g1WrL1TEFXU/8cIJzmh9+YW2
  template:
    metadata:
      name: redis-secret
    type: Opaque
